### PR TITLE
closes #908

### LINKED ISSUE #908: [BUG] Disabling scopes doesn't work if there's only one scope
**Describe the bug**
When only one scope is enabled, disabling that scope has the effect of enabling all scopes.

**To Reproduce**
1. Set up a hotkey with one scope.
2. Get to a state with only that scope enabled (such as defining it as the only initial scope in `<HotkeysProvider />`).
3. Disable that scope.
4. See that the hotkey still works, despite its one scope being disabled.

Please try and add a codesandbox or stackblitz to reproduce the bug:
https://codesandbox.io/s/laughing-zhukovsky-vnrqlj?file=/src/App.js

**Expected behavior**
Disabling the scope of a hotkey should disable the hotkey. And the behavior where disabling all scopes is the same as enabling all scopes is confusing (at least to me).

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome v108
 - Version 4.3.2

### PR DESCRIPTION
**Pull request by sandstone991**

### CODE REVIEW

File: src/HotkeysProvider.tsx [hunk 1]
```diff
@@ -30,44 +30,31 @@ interface Props {
 }
 
 export const HotkeysProvider = ({ initiallyActiveScopes = ['*'], children }: Props) => {
-  const [internalActiveScopes, setInternalActiveScopes] = useState(
-    initiallyActiveScopes?.length > 0 ? initiallyActiveScopes : ['*']
-  )
+  const [internalActiveScopes, setInternalActiveScopes] = useState(initiallyActiveScopes)
```
Comment (JohannesKlauss) [inline src/HotkeysProvider.tsx:33]: In my opinion it would be more user friendly to have all scopes activated by default. At least this is what I would expect as a user. What do you think?

Comment (sandstone991) [reply src/HotkeysProvider.tsx:33]: Well, in my opinion, if the user explicitly gives an empty array, I think they would be expecting no scopes to be active at all. On the other hand, if they pass nothing at all (undefined), they would indeed have all scopes active.

I think this is more fitting, as you may want to initialize with no scopes active at all, and passing an empty array would accomplish this behavior.

Comment (JohannesKlauss) [reply src/HotkeysProvider.tsx:33]: Ah you are right.

**Comment by JohannesKlauss** [comment]
Since this is a breaking change it will be released with version 5. I created a branch called `feature/version_5`. Could you change the target branch of your PR to this branch? Then I can merge it :) Thank you for your work

**Comment by sandstone991** [comment]
You're welcome 😄.
